### ISSUE TITLE
兄弟借问一下

### ISSUE THREAD

**Issue by mkh10086** [Usay23333/TankWarDaily#1]
兄弟学的是马士兵老师最新的2019坦克大战吗？还是老版的？如果是新的，学完能共享一下代码吗？

**Comment by Usay23333** [comment]
最新的

**Comment by Usay23333** [comment]
你现在可以看得到代码吗？我不太会玩Git 我有空就会第一时间上传的

**Comment by mkh10086** [comment]
Git挺简单的，看看这个教程[https://www.liaoxuefeng.com/wiki/896043488029600](https://www.liaoxuefeng.com/wiki/896043488029600)，1个小时就能精通

**Comment by Usay23333** [comment]
好的，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: i386 <notifications@github.com>
发送时间: Wednesday, May 15, 2019 6:11:56 AM
收件人: Usay23333/TankWarDaily
抄送: Sakura; State change
主题: Re: [Usay23333/TankWarDaily] 兄弟借问一下 (#1)


Git挺简单的，看看这个教程https://www.liaoxuefeng.com/wiki/896043488029600，1个小时就能精通

―
